const LOGOS = {
  ATL: require('./ATL.png').default,
  BKN: require('./BKN.png').default,
  BOS: require('./BOS.png').default,
  CHA: require('./CHA.png').default,
  CHI: require('./CHI.png').default,
  CLE: require('./CLE.png').default,
  DAL: require('./DAL.png').default,
  DEN: require('./DEN.png').default,
  DET: require('./DET.png').default,
  GSW: require('./GSW.png').default,
  HOU: require('./HOU.png').default,
  IND: require('./IND.png').default,
  LAC: require('./LAC.png').default,
  LAL: require('./LAL.png').default,
  MEM: require('./MEM.png').default,
  MIA: require('./MIA.png').default,
  MIL: require('./MIL.png').default,
  MIN: require('./MIN.png').default,
  NOP: require('./NOP.png').default,
  NYK: require('./NYK.png').default,
  OKC: require('./OKC.png').default,
  ORL: require('./ORL.png').default,
  PHI: require('./PHI.png').default,
  PHX: require('./PHX.png').default,
  POR: require('./POR.png').default,
  SAC: require('./SAC.png').default,
  SAS: require('./SAS.png').default,
  TOR: require('./TOR.png').default,
  UTA: require('./UTA.png').default,
  WAS: require('./WAS.png').default,
}

export default LOGOS;
